### ISSUE TITLE
Fix file name typo

### ISSUE THREAD

**Issue by thiagodelgado111** [khaueviana/es6-js#1]
* Leia com a voz da Marilu *

Olá, desconhecido senhor Khauezinha! Boderia corrigir o nome deste arquivo?
```
https://github.com/khaueviana/es6-js/blob/master/es6-promisses.js
    =>
https://github.com/khaueviana/es6-js/blob/master/es6-promises.js
```

**Comment by khaueviana** [comment]
Feito!

https://github.com/khaueviana/es6-js/commit/b58258cb57cdcc4cd8e1f77f4986ff3bdb614754
